# Generated by Django 3.1.1 on 2020-10-10 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_remove_breed_related_dogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breeds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_dogs', to='snippets.breed'),
        ),
    ]
